// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "forent": largecategory Resource Client
//
// Command:
// $ goagen
// --design=forent_api/design
// --out=$(GOPATH)/src/forent_api
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ListLargecategoryPath computes a request path to the list action of largecategory.
func ListLargecategoryPath() string {

	return fmt.Sprintf("/v1/largecategories")
}

// Retrieve all largecategories.
func (c *Client) ListLargecategory(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListLargecategoryRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListLargecategoryRequest create the request corresponding to the list action endpoint of the largecategory resource.
func (c *Client) NewListLargecategoryRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.APIKeySigner != nil {
		if err := c.APIKeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
