// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "forent": Application User Types
//
// Command:
// $ goagen
// --design=forent_api/design
// --out=$(GOPATH)/src/forent_api
// --version=v1.3.1

package client
