// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "forent": verification Resource Client
//
// Command:
// $ goagen
// --design=forent_api/design
// --out=$(GOPATH)/src/forent_api
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// CreateVerificationPayload is the verification create action payload.
type CreateVerificationPayload struct {
	// address flag
	Email bool `form:"email" json:"email" xml:"email"`
	// Unique facebook ID
	FacebookID int `form:"facebook_id" json:"facebook_id" xml:"facebook_id"`
	// Unique google ID
	GoogleID int `form:"google_id" json:"google_id" xml:"google_id"`
	// identification flag
	Identification bool `form:"identification" json:"identification" xml:"identification"`
	// user id
	UserID int `form:"user_id" json:"user_id" xml:"user_id"`
}

// CreateVerificationPath computes a request path to the create action of verification.
func CreateVerificationPath() string {

	return fmt.Sprintf("/verifications")
}

// Create new verification
func (c *Client) CreateVerification(ctx context.Context, path string, payload *CreateVerificationPayload, contentType string) (*http.Response, error) {
	req, err := c.NewCreateVerificationRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateVerificationRequest create the request corresponding to the create action endpoint of the verification resource.
func (c *Client) NewCreateVerificationRequest(ctx context.Context, path string, payload *CreateVerificationPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// DeleteVerificationPath computes a request path to the delete action of verification.
func DeleteVerificationPath(verificationID int) string {
	param0 := strconv.Itoa(verificationID)

	return fmt.Sprintf("/verifications/%s", param0)
}

// DeleteVerification makes a request to the delete action endpoint of the verification resource
func (c *Client) DeleteVerification(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDeleteVerificationRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeleteVerificationRequest create the request corresponding to the delete action endpoint of the verification resource.
func (c *Client) NewDeleteVerificationRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ShowVerificationPath computes a request path to the show action of verification.
func ShowVerificationPath(verificationID int) string {
	param0 := strconv.Itoa(verificationID)

	return fmt.Sprintf("/verifications/%s", param0)
}

// Get verification by id
func (c *Client) ShowVerification(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowVerificationRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowVerificationRequest create the request corresponding to the show action endpoint of the verification resource.
func (c *Client) NewShowVerificationRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// UpdateVerificationPayload is the verification update action payload.
type UpdateVerificationPayload struct {
	// address flag
	Email *bool `form:"email,omitempty" json:"email,omitempty" xml:"email,omitempty"`
	// Unique facebook ID
	FacebookID *int `form:"facebook_id,omitempty" json:"facebook_id,omitempty" xml:"facebook_id,omitempty"`
	// Unique google ID
	GoogleID *int `form:"google_id,omitempty" json:"google_id,omitempty" xml:"google_id,omitempty"`
	// identification flag
	Identification *bool `form:"identification,omitempty" json:"identification,omitempty" xml:"identification,omitempty"`
	// user id
	UserID int `form:"user_id" json:"user_id" xml:"user_id"`
}

// UpdateVerificationPath computes a request path to the update action of verification.
func UpdateVerificationPath(verificationID int) string {
	param0 := strconv.Itoa(verificationID)

	return fmt.Sprintf("/verifications/%s", param0)
}

// Change verification data
func (c *Client) UpdateVerification(ctx context.Context, path string, payload *UpdateVerificationPayload, contentType string) (*http.Response, error) {
	req, err := c.NewUpdateVerificationRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewUpdateVerificationRequest create the request corresponding to the update action endpoint of the verification resource.
func (c *Client) NewUpdateVerificationRequest(ctx context.Context, path string, payload *UpdateVerificationPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}
