// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "forent": Application Controllers
//
// Command:
// $ goagen
// --design=forent_api/design
// --out=$(GOPATH)/src/forent_api
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"github.com/goadesign/goa/cors"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// ArticleController is the controller interface for the Article actions.
type ArticleController interface {
	goa.Muxer
	List(*ListArticleContext) error
}

// MountArticleController "mounts" a Article resource controller on the given service.
func MountArticleController(service *goa.Service, ctrl ArticleController) {
	initService(service)
	var h goa.Handler
	service.Mux.Handle("OPTIONS", "/articles", ctrl.MuxHandler("preflight", handleArticleOrigin(cors.HandlePreflight()), nil))

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewListArticleContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*ListArticlePayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.List(rctx)
	}
	h = handleArticleOrigin(h)
	service.Mux.Handle("GET", "/articles", ctrl.MuxHandler("list", h, unmarshalListArticlePayload))
	service.LogInfo("mount", "ctrl", "Article", "action", "List", "route", "GET /articles")
}

// handleArticleOrigin applies the CORS response headers corresponding to the origin.
func handleArticleOrigin(h goa.Handler) goa.Handler {

	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		origin := req.Header.Get("Origin")
		if origin == "" {
			// Not a CORS request
			return h(ctx, rw, req)
		}
		if cors.MatchOrigin(origin, "http://swagger.goa.design") {
			ctx = goa.WithLogContext(ctx, "origin", origin)
			rw.Header().Set("Access-Control-Allow-Origin", origin)
			rw.Header().Set("Vary", "Origin")
			rw.Header().Set("Access-Control-Max-Age", "600")
			rw.Header().Set("Access-Control-Allow-Credentials", "true")
			if acrm := req.Header.Get("Access-Control-Request-Method"); acrm != "" {
				// We are handling a preflight request
				rw.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE")
			}
			return h(ctx, rw, req)
		}

		return h(ctx, rw, req)
	}
}

// unmarshalListArticlePayload unmarshals the request body into the context request data Payload field.
func unmarshalListArticlePayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &listArticlePayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// AuthenticationController is the controller interface for the Authentication actions.
type AuthenticationController interface {
	goa.Muxer
	Sigin(*SiginAuthenticationContext) error
	Signup(*SignupAuthenticationContext) error
}

// MountAuthenticationController "mounts" a Authentication resource controller on the given service.
func MountAuthenticationController(service *goa.Service, ctrl AuthenticationController) {
	initService(service)
	var h goa.Handler
	service.Mux.Handle("OPTIONS", "/signin", ctrl.MuxHandler("preflight", handleAuthenticationOrigin(cors.HandlePreflight()), nil))
	service.Mux.Handle("OPTIONS", "/signup", ctrl.MuxHandler("preflight", handleAuthenticationOrigin(cors.HandlePreflight()), nil))

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewSiginAuthenticationContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*SignupPayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Sigin(rctx)
	}
	h = handleAuthenticationOrigin(h)
	service.Mux.Handle("GET", "/signin", ctrl.MuxHandler("sigin", h, unmarshalSiginAuthenticationPayload))
	service.LogInfo("mount", "ctrl", "Authentication", "action", "Sigin", "route", "GET /signin")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewSignupAuthenticationContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*SignupPayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Signup(rctx)
	}
	h = handleAuthenticationOrigin(h)
	service.Mux.Handle("POST", "/signup", ctrl.MuxHandler("signup", h, unmarshalSignupAuthenticationPayload))
	service.LogInfo("mount", "ctrl", "Authentication", "action", "Signup", "route", "POST /signup")
}

// handleAuthenticationOrigin applies the CORS response headers corresponding to the origin.
func handleAuthenticationOrigin(h goa.Handler) goa.Handler {

	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		origin := req.Header.Get("Origin")
		if origin == "" {
			// Not a CORS request
			return h(ctx, rw, req)
		}
		if cors.MatchOrigin(origin, "http://swagger.goa.design") {
			ctx = goa.WithLogContext(ctx, "origin", origin)
			rw.Header().Set("Access-Control-Allow-Origin", origin)
			rw.Header().Set("Vary", "Origin")
			rw.Header().Set("Access-Control-Max-Age", "600")
			rw.Header().Set("Access-Control-Allow-Credentials", "true")
			if acrm := req.Header.Get("Access-Control-Request-Method"); acrm != "" {
				// We are handling a preflight request
				rw.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE")
			}
			return h(ctx, rw, req)
		}

		return h(ctx, rw, req)
	}
}

// unmarshalSiginAuthenticationPayload unmarshals the request body into the context request data Payload field.
func unmarshalSiginAuthenticationPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &signupPayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// unmarshalSignupAuthenticationPayload unmarshals the request body into the context request data Payload field.
func unmarshalSignupAuthenticationPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &signupPayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// CategoryController is the controller interface for the Category actions.
type CategoryController interface {
	goa.Muxer
	List(*ListCategoryContext) error
}

// MountCategoryController "mounts" a Category resource controller on the given service.
func MountCategoryController(service *goa.Service, ctrl CategoryController) {
	initService(service)
	var h goa.Handler
	service.Mux.Handle("OPTIONS", "/categories", ctrl.MuxHandler("preflight", handleCategoryOrigin(cors.HandlePreflight()), nil))

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewListCategoryContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*ListCategoryPayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.List(rctx)
	}
	h = handleCategoryOrigin(h)
	service.Mux.Handle("GET", "/categories", ctrl.MuxHandler("list", h, unmarshalListCategoryPayload))
	service.LogInfo("mount", "ctrl", "Category", "action", "List", "route", "GET /categories")
}

// handleCategoryOrigin applies the CORS response headers corresponding to the origin.
func handleCategoryOrigin(h goa.Handler) goa.Handler {

	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		origin := req.Header.Get("Origin")
		if origin == "" {
			// Not a CORS request
			return h(ctx, rw, req)
		}
		if cors.MatchOrigin(origin, "http://swagger.goa.design") {
			ctx = goa.WithLogContext(ctx, "origin", origin)
			rw.Header().Set("Access-Control-Allow-Origin", origin)
			rw.Header().Set("Vary", "Origin")
			rw.Header().Set("Access-Control-Max-Age", "600")
			rw.Header().Set("Access-Control-Allow-Credentials", "true")
			if acrm := req.Header.Get("Access-Control-Request-Method"); acrm != "" {
				// We are handling a preflight request
				rw.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE")
			}
			return h(ctx, rw, req)
		}

		return h(ctx, rw, req)
	}
}

// unmarshalListCategoryPayload unmarshals the request body into the context request data Payload field.
func unmarshalListCategoryPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &listCategoryPayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// CommentController is the controller interface for the Comment actions.
type CommentController interface {
	goa.Muxer
	Create(*CreateCommentContext) error
	List(*ListCommentContext) error
	Show(*ShowCommentContext) error
}

// MountCommentController "mounts" a Comment resource controller on the given service.
func MountCommentController(service *goa.Service, ctrl CommentController) {
	initService(service)
	var h goa.Handler
	service.Mux.Handle("OPTIONS", "/comments", ctrl.MuxHandler("preflight", handleCommentOrigin(cors.HandlePreflight()), nil))
	service.Mux.Handle("OPTIONS", "/comments/:itemID", ctrl.MuxHandler("preflight", handleCommentOrigin(cors.HandlePreflight()), nil))

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewCreateCommentContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*CreateCommentPayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Create(rctx)
	}
	h = handleCommentOrigin(h)
	service.Mux.Handle("POST", "/comments", ctrl.MuxHandler("create", h, unmarshalCreateCommentPayload))
	service.LogInfo("mount", "ctrl", "Comment", "action", "Create", "route", "POST /comments")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewListCommentContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.List(rctx)
	}
	h = handleCommentOrigin(h)
	service.Mux.Handle("GET", "/comments", ctrl.MuxHandler("list", h, nil))
	service.LogInfo("mount", "ctrl", "Comment", "action", "List", "route", "GET /comments")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewShowCommentContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Show(rctx)
	}
	h = handleCommentOrigin(h)
	service.Mux.Handle("GET", "/comments/:itemID", ctrl.MuxHandler("show", h, nil))
	service.LogInfo("mount", "ctrl", "Comment", "action", "Show", "route", "GET /comments/:itemID")
}

// handleCommentOrigin applies the CORS response headers corresponding to the origin.
func handleCommentOrigin(h goa.Handler) goa.Handler {

	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		origin := req.Header.Get("Origin")
		if origin == "" {
			// Not a CORS request
			return h(ctx, rw, req)
		}
		if cors.MatchOrigin(origin, "http://swagger.goa.design") {
			ctx = goa.WithLogContext(ctx, "origin", origin)
			rw.Header().Set("Access-Control-Allow-Origin", origin)
			rw.Header().Set("Vary", "Origin")
			rw.Header().Set("Access-Control-Max-Age", "600")
			rw.Header().Set("Access-Control-Allow-Credentials", "true")
			if acrm := req.Header.Get("Access-Control-Request-Method"); acrm != "" {
				// We are handling a preflight request
				rw.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE")
			}
			return h(ctx, rw, req)
		}

		return h(ctx, rw, req)
	}
}

// unmarshalCreateCommentPayload unmarshals the request body into the context request data Payload field.
func unmarshalCreateCommentPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &createCommentPayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// ItemController is the controller interface for the Item actions.
type ItemController interface {
	goa.Muxer
	Create(*CreateItemContext) error
	Delete(*DeleteItemContext) error
	List(*ListItemContext) error
	Update(*UpdateItemContext) error
}

// MountItemController "mounts" a Item resource controller on the given service.
func MountItemController(service *goa.Service, ctrl ItemController) {
	initService(service)
	var h goa.Handler
	service.Mux.Handle("OPTIONS", "/items", ctrl.MuxHandler("preflight", handleItemOrigin(cors.HandlePreflight()), nil))

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewCreateItemContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*CreateItemPayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Create(rctx)
	}
	h = handleSecurity("jwt", h, "api:access")
	h = handleItemOrigin(h)
	service.Mux.Handle("POST", "/items", ctrl.MuxHandler("create", h, unmarshalCreateItemPayload))
	service.LogInfo("mount", "ctrl", "Item", "action", "Create", "route", "POST /items", "security", "jwt")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewDeleteItemContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*DeleteItemPayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Delete(rctx)
	}
	h = handleSecurity("jwt", h, "api:access")
	h = handleItemOrigin(h)
	service.Mux.Handle("DELETE", "/items", ctrl.MuxHandler("delete", h, unmarshalDeleteItemPayload))
	service.LogInfo("mount", "ctrl", "Item", "action", "Delete", "route", "DELETE /items", "security", "jwt")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewListItemContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*ListItemPayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.List(rctx)
	}
	h = handleItemOrigin(h)
	service.Mux.Handle("GET", "/items", ctrl.MuxHandler("list", h, unmarshalListItemPayload))
	service.LogInfo("mount", "ctrl", "Item", "action", "List", "route", "GET /items")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewUpdateItemContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*UpdateItemPayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Update(rctx)
	}
	h = handleSecurity("jwt", h, "api:access")
	h = handleItemOrigin(h)
	service.Mux.Handle("PUT", "/items", ctrl.MuxHandler("update", h, unmarshalUpdateItemPayload))
	service.LogInfo("mount", "ctrl", "Item", "action", "Update", "route", "PUT /items", "security", "jwt")
}

// handleItemOrigin applies the CORS response headers corresponding to the origin.
func handleItemOrigin(h goa.Handler) goa.Handler {

	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		origin := req.Header.Get("Origin")
		if origin == "" {
			// Not a CORS request
			return h(ctx, rw, req)
		}
		if cors.MatchOrigin(origin, "http://swagger.goa.design") {
			ctx = goa.WithLogContext(ctx, "origin", origin)
			rw.Header().Set("Access-Control-Allow-Origin", origin)
			rw.Header().Set("Vary", "Origin")
			rw.Header().Set("Access-Control-Max-Age", "600")
			rw.Header().Set("Access-Control-Allow-Credentials", "true")
			if acrm := req.Header.Get("Access-Control-Request-Method"); acrm != "" {
				// We are handling a preflight request
				rw.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE")
			}
			return h(ctx, rw, req)
		}

		return h(ctx, rw, req)
	}
}

// unmarshalCreateItemPayload unmarshals the request body into the context request data Payload field.
func unmarshalCreateItemPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &createItemPayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// unmarshalDeleteItemPayload unmarshals the request body into the context request data Payload field.
func unmarshalDeleteItemPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &deleteItemPayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// unmarshalListItemPayload unmarshals the request body into the context request data Payload field.
func unmarshalListItemPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &listItemPayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// unmarshalUpdateItemPayload unmarshals the request body into the context request data Payload field.
func unmarshalUpdateItemPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &updateItemPayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// LargecategoryController is the controller interface for the Largecategory actions.
type LargecategoryController interface {
	goa.Muxer
	List(*ListLargecategoryContext) error
}

// MountLargecategoryController "mounts" a Largecategory resource controller on the given service.
func MountLargecategoryController(service *goa.Service, ctrl LargecategoryController) {
	initService(service)
	var h goa.Handler
	service.Mux.Handle("OPTIONS", "/largecategories", ctrl.MuxHandler("preflight", handleLargecategoryOrigin(cors.HandlePreflight()), nil))

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewListLargecategoryContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.List(rctx)
	}
	h = handleLargecategoryOrigin(h)
	service.Mux.Handle("GET", "/largecategories", ctrl.MuxHandler("list", h, nil))
	service.LogInfo("mount", "ctrl", "Largecategory", "action", "List", "route", "GET /largecategories")
}

// handleLargecategoryOrigin applies the CORS response headers corresponding to the origin.
func handleLargecategoryOrigin(h goa.Handler) goa.Handler {

	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		origin := req.Header.Get("Origin")
		if origin == "" {
			// Not a CORS request
			return h(ctx, rw, req)
		}
		if cors.MatchOrigin(origin, "http://swagger.goa.design") {
			ctx = goa.WithLogContext(ctx, "origin", origin)
			rw.Header().Set("Access-Control-Allow-Origin", origin)
			rw.Header().Set("Vary", "Origin")
			rw.Header().Set("Access-Control-Max-Age", "600")
			rw.Header().Set("Access-Control-Allow-Credentials", "true")
			if acrm := req.Header.Get("Access-Control-Request-Method"); acrm != "" {
				// We are handling a preflight request
				rw.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE")
			}
			return h(ctx, rw, req)
		}

		return h(ctx, rw, req)
	}
}

// MiddlecategoryController is the controller interface for the Middlecategory actions.
type MiddlecategoryController interface {
	goa.Muxer
	List(*ListMiddlecategoryContext) error
}

// MountMiddlecategoryController "mounts" a Middlecategory resource controller on the given service.
func MountMiddlecategoryController(service *goa.Service, ctrl MiddlecategoryController) {
	initService(service)
	var h goa.Handler
	service.Mux.Handle("OPTIONS", "/middlecategories", ctrl.MuxHandler("preflight", handleMiddlecategoryOrigin(cors.HandlePreflight()), nil))

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewListMiddlecategoryContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*ListMiddlecategoryPayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.List(rctx)
	}
	h = handleMiddlecategoryOrigin(h)
	service.Mux.Handle("GET", "/middlecategories", ctrl.MuxHandler("list", h, unmarshalListMiddlecategoryPayload))
	service.LogInfo("mount", "ctrl", "Middlecategory", "action", "List", "route", "GET /middlecategories")
}

// handleMiddlecategoryOrigin applies the CORS response headers corresponding to the origin.
func handleMiddlecategoryOrigin(h goa.Handler) goa.Handler {

	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		origin := req.Header.Get("Origin")
		if origin == "" {
			// Not a CORS request
			return h(ctx, rw, req)
		}
		if cors.MatchOrigin(origin, "http://swagger.goa.design") {
			ctx = goa.WithLogContext(ctx, "origin", origin)
			rw.Header().Set("Access-Control-Allow-Origin", origin)
			rw.Header().Set("Vary", "Origin")
			rw.Header().Set("Access-Control-Max-Age", "600")
			rw.Header().Set("Access-Control-Allow-Credentials", "true")
			if acrm := req.Header.Get("Access-Control-Request-Method"); acrm != "" {
				// We are handling a preflight request
				rw.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE")
			}
			return h(ctx, rw, req)
		}

		return h(ctx, rw, req)
	}
}

// unmarshalListMiddlecategoryPayload unmarshals the request body into the context request data Payload field.
func unmarshalListMiddlecategoryPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &listMiddlecategoryPayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// OfferController is the controller interface for the Offer actions.
type OfferController interface {
	goa.Muxer
	Create(*CreateOfferContext) error
	Show(*ShowOfferContext) error
}

// MountOfferController "mounts" a Offer resource controller on the given service.
func MountOfferController(service *goa.Service, ctrl OfferController) {
	initService(service)
	var h goa.Handler
	service.Mux.Handle("OPTIONS", "/offers", ctrl.MuxHandler("preflight", handleOfferOrigin(cors.HandlePreflight()), nil))
	service.Mux.Handle("OPTIONS", "/offers/:ownerID", ctrl.MuxHandler("preflight", handleOfferOrigin(cors.HandlePreflight()), nil))

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewCreateOfferContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*CreateOfferPayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Create(rctx)
	}
	h = handleOfferOrigin(h)
	service.Mux.Handle("POST", "/offers", ctrl.MuxHandler("create", h, unmarshalCreateOfferPayload))
	service.LogInfo("mount", "ctrl", "Offer", "action", "Create", "route", "POST /offers")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewShowOfferContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Show(rctx)
	}
	h = handleOfferOrigin(h)
	service.Mux.Handle("GET", "/offers/:ownerID", ctrl.MuxHandler("show", h, nil))
	service.LogInfo("mount", "ctrl", "Offer", "action", "Show", "route", "GET /offers/:ownerID")
}

// handleOfferOrigin applies the CORS response headers corresponding to the origin.
func handleOfferOrigin(h goa.Handler) goa.Handler {

	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		origin := req.Header.Get("Origin")
		if origin == "" {
			// Not a CORS request
			return h(ctx, rw, req)
		}
		if cors.MatchOrigin(origin, "http://swagger.goa.design") {
			ctx = goa.WithLogContext(ctx, "origin", origin)
			rw.Header().Set("Access-Control-Allow-Origin", origin)
			rw.Header().Set("Vary", "Origin")
			rw.Header().Set("Access-Control-Max-Age", "600")
			rw.Header().Set("Access-Control-Allow-Credentials", "true")
			if acrm := req.Header.Get("Access-Control-Request-Method"); acrm != "" {
				// We are handling a preflight request
				rw.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE")
			}
			return h(ctx, rw, req)
		}

		return h(ctx, rw, req)
	}
}

// unmarshalCreateOfferPayload unmarshals the request body into the context request data Payload field.
func unmarshalCreateOfferPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &createOfferPayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// PlaceController is the controller interface for the Place actions.
type PlaceController interface {
	goa.Muxer
	List(*ListPlaceContext) error
}

// MountPlaceController "mounts" a Place resource controller on the given service.
func MountPlaceController(service *goa.Service, ctrl PlaceController) {
	initService(service)
	var h goa.Handler
	service.Mux.Handle("OPTIONS", "/places", ctrl.MuxHandler("preflight", handlePlaceOrigin(cors.HandlePreflight()), nil))

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewListPlaceContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*ListPlacePayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.List(rctx)
	}
	h = handlePlaceOrigin(h)
	service.Mux.Handle("GET", "/places", ctrl.MuxHandler("list", h, unmarshalListPlacePayload))
	service.LogInfo("mount", "ctrl", "Place", "action", "List", "route", "GET /places")
}

// handlePlaceOrigin applies the CORS response headers corresponding to the origin.
func handlePlaceOrigin(h goa.Handler) goa.Handler {

	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		origin := req.Header.Get("Origin")
		if origin == "" {
			// Not a CORS request
			return h(ctx, rw, req)
		}
		if cors.MatchOrigin(origin, "http://swagger.goa.design") {
			ctx = goa.WithLogContext(ctx, "origin", origin)
			rw.Header().Set("Access-Control-Allow-Origin", origin)
			rw.Header().Set("Vary", "Origin")
			rw.Header().Set("Access-Control-Max-Age", "600")
			rw.Header().Set("Access-Control-Allow-Credentials", "true")
			if acrm := req.Header.Get("Access-Control-Request-Method"); acrm != "" {
				// We are handling a preflight request
				rw.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE")
			}
			return h(ctx, rw, req)
		}

		return h(ctx, rw, req)
	}
}

// unmarshalListPlacePayload unmarshals the request body into the context request data Payload field.
func unmarshalListPlacePayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &listPlacePayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// ProfileController is the controller interface for the Profile actions.
type ProfileController interface {
	goa.Muxer
	Create(*CreateProfileContext) error
	Delete(*DeleteProfileContext) error
	Show(*ShowProfileContext) error
	Update(*UpdateProfileContext) error
}

// MountProfileController "mounts" a Profile resource controller on the given service.
func MountProfileController(service *goa.Service, ctrl ProfileController) {
	initService(service)
	var h goa.Handler
	service.Mux.Handle("OPTIONS", "/profiles", ctrl.MuxHandler("preflight", handleProfileOrigin(cors.HandlePreflight()), nil))

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewCreateProfileContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*CreateProfilePayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Create(rctx)
	}
	h = handleSecurity("jwt", h, "api:access")
	h = handleProfileOrigin(h)
	service.Mux.Handle("POST", "/profiles", ctrl.MuxHandler("create", h, unmarshalCreateProfilePayload))
	service.LogInfo("mount", "ctrl", "Profile", "action", "Create", "route", "POST /profiles", "security", "jwt")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewDeleteProfileContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Delete(rctx)
	}
	h = handleSecurity("jwt", h, "api:access")
	h = handleProfileOrigin(h)
	service.Mux.Handle("DELETE", "/profiles", ctrl.MuxHandler("delete", h, nil))
	service.LogInfo("mount", "ctrl", "Profile", "action", "Delete", "route", "DELETE /profiles", "security", "jwt")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewShowProfileContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*ShowProfilePayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Show(rctx)
	}
	h = handleProfileOrigin(h)
	service.Mux.Handle("GET", "/profiles", ctrl.MuxHandler("show", h, unmarshalShowProfilePayload))
	service.LogInfo("mount", "ctrl", "Profile", "action", "Show", "route", "GET /profiles")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewUpdateProfileContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*UpdateProfilePayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Update(rctx)
	}
	h = handleSecurity("jwt", h, "api:access")
	h = handleProfileOrigin(h)
	service.Mux.Handle("PUT", "/profiles", ctrl.MuxHandler("update", h, unmarshalUpdateProfilePayload))
	service.LogInfo("mount", "ctrl", "Profile", "action", "Update", "route", "PUT /profiles", "security", "jwt")
}

// handleProfileOrigin applies the CORS response headers corresponding to the origin.
func handleProfileOrigin(h goa.Handler) goa.Handler {

	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		origin := req.Header.Get("Origin")
		if origin == "" {
			// Not a CORS request
			return h(ctx, rw, req)
		}
		if cors.MatchOrigin(origin, "http://swagger.goa.design") {
			ctx = goa.WithLogContext(ctx, "origin", origin)
			rw.Header().Set("Access-Control-Allow-Origin", origin)
			rw.Header().Set("Vary", "Origin")
			rw.Header().Set("Access-Control-Max-Age", "600")
			rw.Header().Set("Access-Control-Allow-Credentials", "true")
			if acrm := req.Header.Get("Access-Control-Request-Method"); acrm != "" {
				// We are handling a preflight request
				rw.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE")
			}
			return h(ctx, rw, req)
		}

		return h(ctx, rw, req)
	}
}

// unmarshalCreateProfilePayload unmarshals the request body into the context request data Payload field.
func unmarshalCreateProfilePayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &createProfilePayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// unmarshalShowProfilePayload unmarshals the request body into the context request data Payload field.
func unmarshalShowProfilePayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &showProfilePayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// unmarshalUpdateProfilePayload unmarshals the request body into the context request data Payload field.
func unmarshalUpdateProfilePayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &updateProfilePayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// VerificationController is the controller interface for the Verification actions.
type VerificationController interface {
	goa.Muxer
	Create(*CreateVerificationContext) error
	Delete(*DeleteVerificationContext) error
	Show(*ShowVerificationContext) error
	Update(*UpdateVerificationContext) error
}

// MountVerificationController "mounts" a Verification resource controller on the given service.
func MountVerificationController(service *goa.Service, ctrl VerificationController) {
	initService(service)
	var h goa.Handler
	service.Mux.Handle("OPTIONS", "/verifications", ctrl.MuxHandler("preflight", handleVerificationOrigin(cors.HandlePreflight()), nil))
	service.Mux.Handle("OPTIONS", "/verifications/:verificationID", ctrl.MuxHandler("preflight", handleVerificationOrigin(cors.HandlePreflight()), nil))

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewCreateVerificationContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*CreateVerificationPayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Create(rctx)
	}
	h = handleVerificationOrigin(h)
	service.Mux.Handle("POST", "/verifications", ctrl.MuxHandler("create", h, unmarshalCreateVerificationPayload))
	service.LogInfo("mount", "ctrl", "Verification", "action", "Create", "route", "POST /verifications")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewDeleteVerificationContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Delete(rctx)
	}
	h = handleVerificationOrigin(h)
	service.Mux.Handle("DELETE", "/verifications/:verificationID", ctrl.MuxHandler("delete", h, nil))
	service.LogInfo("mount", "ctrl", "Verification", "action", "Delete", "route", "DELETE /verifications/:verificationID")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewShowVerificationContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Show(rctx)
	}
	h = handleVerificationOrigin(h)
	service.Mux.Handle("GET", "/verifications/:verificationID", ctrl.MuxHandler("show", h, nil))
	service.LogInfo("mount", "ctrl", "Verification", "action", "Show", "route", "GET /verifications/:verificationID")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewUpdateVerificationContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*UpdateVerificationPayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Update(rctx)
	}
	h = handleVerificationOrigin(h)
	service.Mux.Handle("PUT", "/verifications/:verificationID", ctrl.MuxHandler("update", h, unmarshalUpdateVerificationPayload))
	service.LogInfo("mount", "ctrl", "Verification", "action", "Update", "route", "PUT /verifications/:verificationID")
}

// handleVerificationOrigin applies the CORS response headers corresponding to the origin.
func handleVerificationOrigin(h goa.Handler) goa.Handler {

	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		origin := req.Header.Get("Origin")
		if origin == "" {
			// Not a CORS request
			return h(ctx, rw, req)
		}
		if cors.MatchOrigin(origin, "http://swagger.goa.design") {
			ctx = goa.WithLogContext(ctx, "origin", origin)
			rw.Header().Set("Access-Control-Allow-Origin", origin)
			rw.Header().Set("Vary", "Origin")
			rw.Header().Set("Access-Control-Max-Age", "600")
			rw.Header().Set("Access-Control-Allow-Credentials", "true")
			if acrm := req.Header.Get("Access-Control-Request-Method"); acrm != "" {
				// We are handling a preflight request
				rw.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE")
			}
			return h(ctx, rw, req)
		}

		return h(ctx, rw, req)
	}
}

// unmarshalCreateVerificationPayload unmarshals the request body into the context request data Payload field.
func unmarshalCreateVerificationPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &createVerificationPayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}

// unmarshalUpdateVerificationPayload unmarshals the request body into the context request data Payload field.
func unmarshalUpdateVerificationPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &updateVerificationPayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}
