// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "forent": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=forent_api/design
// --out=$(GOPATH)/src/forent_api
// --version=v1.3.1

package app

import (
	"fmt"
	"strings"
)

// CommentHref returns the resource href.
func CommentHref(itemID interface{}) string {
	paramitemID := strings.TrimLeftFunc(fmt.Sprintf("%v", itemID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/comments/%v", paramitemID)
}

// ProfileHref returns the resource href.
func ProfileHref() string {
	return "/profiles"
}

// VerificationHref returns the resource href.
func VerificationHref(verificationID interface{}) string {
	paramverificationID := strings.TrimLeftFunc(fmt.Sprintf("%v", verificationID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/verifications/%v", paramverificationID)
}
