// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "forent": Model Helpers
//
// Command:
// $ goagen
// --design=forent_api/design
// --out=$(GOPATH)/src/forent_api
// --version=v1.3.1

package models

import (
	"context"
	"forent_api/app"
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"time"
)

// MediaType Retrieval Functions

// ListMiddlecategory returns an array of view: default.
func (m *MiddleCategoryDB) ListMiddlecategory(ctx context.Context, largeCategoryID int) []*app.Middlecategory {
	defer goa.MeasureSince([]string{"goa", "db", "middlecategory", "listmiddlecategory"}, time.Now())

	var native []*MiddleCategory
	var objs []*app.Middlecategory
	err := m.Db.Scopes(MiddleCategoryFilterByLargeCategory(largeCategoryID, m.Db)).Table(m.TableName()).Find(&native).Error

	if err != nil {
		goa.LogError(ctx, "error listing MiddleCategory", "error", err.Error())
		return objs
	}

	for _, t := range native {
		objs = append(objs, t.MiddleCategoryToMiddlecategory())
	}

	return objs
}

// MiddleCategoryToMiddlecategory loads a MiddleCategory and builds the default view of media type Middlecategory.
func (m *MiddleCategory) MiddleCategoryToMiddlecategory() *app.Middlecategory {
	middlecategory := &app.Middlecategory{}
	middlecategory.ID = m.ID
	middlecategory.LargeCategoryID = m.LargeCategoryID
	middlecategory.Name = m.Name
	middlecategory.NameBase = m.NameBase
	middlecategory.NameEn = m.NameEn

	return middlecategory
}

// OneMiddlecategory loads a MiddleCategory and builds the default view of media type Middlecategory.
func (m *MiddleCategoryDB) OneMiddlecategory(ctx context.Context, id int, largeCategoryID int) (*app.Middlecategory, error) {
	defer goa.MeasureSince([]string{"goa", "db", "middlecategory", "onemiddlecategory"}, time.Now())

	var native MiddleCategory
	err := m.Db.Scopes(MiddleCategoryFilterByLargeCategory(largeCategoryID, m.Db)).Table(m.TableName()).Preload("Categories").Preload("LargeCategory").Where("id = ?", id).Find(&native).Error

	if err != nil && err != gorm.ErrRecordNotFound {
		goa.LogError(ctx, "error getting MiddleCategory", "error", err.Error())
		return nil, err
	}

	view := *native.MiddleCategoryToMiddlecategory()
	return &view, err
}
