// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "forent": Models
//
// Command:
// $ goagen
// --design=forent_api/design
// --out=$(GOPATH)/src/forent_api
// --version=v1.3.1

package models

import (
	"context"
	"forent_api/app"
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"time"
)

// Verification Model
type Verification struct {
	ID             int `gorm:"primary_key"` // This is the verification Model PK field
	Email          bool
	FacebookID     int
	GoogleID       int
	Identification bool
	UserID         int        // has one Verification
	CreatedAt      time.Time  // timestamp
	DeletedAt      *time.Time // nullable timestamp (soft delete)
	UpdatedAt      time.Time  // timestamp
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m Verification) TableName() string {
	return "verifications"

}

// VerificationDB is the implementation of the storage interface for
// Verification.
type VerificationDB struct {
	Db *gorm.DB
}

// NewVerificationDB creates a new storage type.
func NewVerificationDB(db *gorm.DB) *VerificationDB {
	return &VerificationDB{Db: db}
}

// DB returns the underlying database.
func (m *VerificationDB) DB() interface{} {
	return m.Db
}

// VerificationStorage represents the storage interface.
type VerificationStorage interface {
	DB() interface{}
	List(ctx context.Context) ([]*Verification, error)
	Get(ctx context.Context, id int) (*Verification, error)
	Add(ctx context.Context, verification *Verification) error
	Update(ctx context.Context, verification *Verification) error
	Delete(ctx context.Context, id int) error

	ListVerification(ctx context.Context) []*app.Verification
	OneVerification(ctx context.Context, id int) (*app.Verification, error)
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m *VerificationDB) TableName() string {
	return "verifications"

}

// CRUD Functions

// Get returns a single Verification as a Database Model
// This is more for use internally, and probably not what you want in  your controllers
func (m *VerificationDB) Get(ctx context.Context, id int) (*Verification, error) {
	defer goa.MeasureSince([]string{"goa", "db", "verification", "get"}, time.Now())

	var native Verification
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of Verification
func (m *VerificationDB) List(ctx context.Context) ([]*Verification, error) {
	defer goa.MeasureSince([]string{"goa", "db", "verification", "list"}, time.Now())

	var objs []*Verification
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *VerificationDB) Add(ctx context.Context, model *Verification) error {
	defer goa.MeasureSince([]string{"goa", "db", "verification", "add"}, time.Now())

	err := m.Db.Create(model).Error
	if err != nil {
		goa.LogError(ctx, "error adding Verification", "error", err.Error())
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *VerificationDB) Update(ctx context.Context, model *Verification) error {
	defer goa.MeasureSince([]string{"goa", "db", "verification", "update"}, time.Now())

	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		goa.LogError(ctx, "error updating Verification", "error", err.Error())
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *VerificationDB) Delete(ctx context.Context, id int) error {
	defer goa.MeasureSince([]string{"goa", "db", "verification", "delete"}, time.Now())

	var obj Verification

	err := m.Db.Delete(&obj, id).Error

	if err != nil {
		goa.LogError(ctx, "error deleting Verification", "error", err.Error())
		return err
	}

	return nil
}
